// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn7TOsfC82BCYYWPy10SFt-Rke4MHb1CA',
    appId: '1:854811938553:web:2011cd269b93ef3df65c28',
    messagingSenderId: '854811938553',
    projectId: 'hafiz-app-3e264',
    authDomain: 'hafiz-app-3e264.firebaseapp.com',
    storageBucket: 'hafiz-app-3e264.appspot.com',
    measurementId: 'G-YVNBPGLVX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjYChEXf0NJRDL7VJhDWe_xouOORsGrI',
    appId: '1:854811938553:android:7a72ac4049b699cff65c28',
    messagingSenderId: '854811938553',
    projectId: 'hafiz-app-3e264',
    storageBucket: 'hafiz-app-3e264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iQVQW3O-I7DFXc-i6G_MtefYV3Ac7_U',
    appId: '1:854811938553:ios:a910535fc431cfa8f65c28',
    messagingSenderId: '854811938553',
    projectId: 'hafiz-app-3e264',
    storageBucket: 'hafiz-app-3e264.appspot.com',
    iosBundleId: 'com.learn.flutter.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iQVQW3O-I7DFXc-i6G_MtefYV3Ac7_U',
    appId: '1:854811938553:ios:d209b4a3d1a2a0f2f65c28',
    messagingSenderId: '854811938553',
    projectId: 'hafiz-app-3e264',
    storageBucket: 'hafiz-app-3e264.appspot.com',
    iosBundleId: 'com.learn.flutter.learningFlutter.RunnerTests',
  );
}
